package test.demo.activity.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;



import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

import test.demo.activity.db.entiry.BlackList;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BLACK_LIST".
*/
public class BlackListDao extends AbstractDao<BlackList, Long> {

    public static final String TABLENAME = "BLACK_LIST";

    /**
     * Properties of entity BlackList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property _id = new Property(0, Long.class, "_id", true, "_id");
        public final static Property Tag5A = new Property(1, String.class, "tag5A", false, "TAG5_A");
        public final static Property Tag5F34 = new Property(2, String.class, "tag5F34", false, "TAG5_F34");
    }


    public BlackListDao(DaoConfig config) {
        super(config);
    }
    
    public BlackListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BLACK_LIST\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: _id
                "\"TAG5_A\" TEXT," + // 1: tag5A
                "\"TAG5_F34\" TEXT);"); // 2: tag5F34
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BLACK_LIST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BlackList entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String tag5A = entity.getTag5A();
        if (tag5A != null) {
            stmt.bindString(2, tag5A);
        }
 
        String tag5F34 = entity.getTag5F34();
        if (tag5F34 != null) {
            stmt.bindString(3, tag5F34);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BlackList entity) {
        stmt.clearBindings();
 
        Long _id = entity.get_id();
        if (_id != null) {
            stmt.bindLong(1, _id);
        }
 
        String tag5A = entity.getTag5A();
        if (tag5A != null) {
            stmt.bindString(2, tag5A);
        }
 
        String tag5F34 = entity.getTag5F34();
        if (tag5F34 != null) {
            stmt.bindString(3, tag5F34);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BlackList readEntity(Cursor cursor, int offset) {
        BlackList entity = new BlackList( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // _id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // tag5A
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // tag5F34
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BlackList entity, int offset) {
        entity.set_id(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTag5A(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTag5F34(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BlackList entity, long rowId) {
        entity.set_id(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BlackList entity) {
        if(entity != null) {
            return entity.get_id();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BlackList entity) {
        return entity.get_id() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
