package test.demo.activity.db.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;



import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;

import test.demo.activity.db.entiry.EMVBatchUploadData;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "EMVBatchUploadData".
*/
public class EMVBatchUploadDataDao extends AbstractDao<EMVBatchUploadData, Long> {

    public static final String TABLENAME = "EMVBatchUploadData";

    /**
     * Properties of entity EMVBatchUploadData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Tag82 = new Property(1, String.class, "tag82", false, "TAG82");
        public final static Property Tag9F36 = new Property(2, String.class, "tag9F36", false, "TAG9F36");
        public final static Property Tag9F07 = new Property(3, String.class, "tag9F07", false, "TAG9F07");
        public final static Property Tag9F27 = new Property(4, String.class, "tag9F27", false, "TAG9F27");
        public final static Property Tag8E = new Property(5, String.class, "tag8E", false, "TAG8E");
        public final static Property Tag9F34 = new Property(6, String.class, "tag9F34", false, "TAG9F34");
        public final static Property Tag9F1E = new Property(7, String.class, "tag9F1E", false, "TAG9F1E");
        public final static Property Tag9F0D = new Property(8, String.class, "tag9F0D", false, "TAG9F0D");
        public final static Property Tag9F0E = new Property(9, String.class, "tag9F0E", false, "TAG9F0E");
        public final static Property Tag9F0F = new Property(10, String.class, "tag9F0F", false, "TAG9F0F");
        public final static Property Tag9F10 = new Property(11, String.class, "tag9F10", false, "TAG9F10");
        public final static Property TagDF31 = new Property(12, String.class, "tagDF31", false, "TAGDF31");
        public final static Property Tag9F33 = new Property(13, String.class, "tag9F33", false, "TAG9F33");
        public final static Property Tag9F35 = new Property(14, String.class, "tag9F35", false, "TAG9F35");
        public final static Property Tag95 = new Property(15, String.class, "tag95", false, "TAG95");
        public final static Property Tag9B = new Property(16, String.class, "tag9B", false, "TAG9B");
        public final static Property Tag9F26 = new Property(17, String.class, "tag9F26", false, "TAG9F26");
        public final static Property Tag9F37 = new Property(18, String.class, "tag9F37", false, "TAG9F37");
        public final static Property Tag9F01 = new Property(19, String.class, "tag9F01", false, "TAG9F01");
        public final static Property Tag9F02 = new Property(20, String.class, "tag9F02", false, "TAG9F02");
        public final static Property Tag9F03 = new Property(21, String.class, "tag9F03", false, "TAG9F03");
        public final static Property Tag5F25 = new Property(22, String.class, "tag5F25", false, "TAG5F25");
        public final static Property Tag5F24 = new Property(23, String.class, "tag5F24", false, "TAG5F24");
        public final static Property Tag5A = new Property(24, String.class, "tag5A", false, "TAG5A");
        public final static Property Tag5F34 = new Property(25, String.class, "tag5F34", false, "TAG5F34");
        public final static Property Tag5F28 = new Property(26, String.class, "tag5F28", false, "TAG5F28");
        public final static Property Tag9F15 = new Property(27, String.class, "tag9F15", false, "TAG9F15");
        public final static Property Tag9F16 = new Property(28, String.class, "tag9F16", false, "TAG9F16");
        public final static Property Tag9F1A = new Property(29, String.class, "tag9F1A", false, "TAG9F1A");
        public final static Property Tag9F1C = new Property(30, String.class, "tag9F1C", false, "TAG9F1C");
        public final static Property Tag57 = new Property(31, String.class, "tag57", false, "TAG57");
        public final static Property Tag81 = new Property(32, String.class, "tag81", false, "TAG81");
        public final static Property Tag5F2A = new Property(33, String.class, "tag5F2A", false, "TAG5F2A");
        public final static Property Tag9A = new Property(34, String.class, "tag9A", false, "TAG9A");
        public final static Property Tag9F21 = new Property(35, String.class, "tag9F21", false, "TAG9F21");
        public final static Property Tag9C = new Property(36, String.class, "tag9C", false, "TAG9C");
        public final static Property Tag9F24 = new Property(37, String.class, "tag9F24", false, "TAG9F24");
        public final static Property Tag9F19 = new Property(38, String.class, "tag9F19", false, "TAG9F19");
        public final static Property Tag9F06 = new Property(39, String.class, "tag9F06", false, "TAG9F06");
        public final static Property Tag8A = new Property(40, String.class, "tag8A", false, "TAG8A");
        public final static Property Tag9F39 = new Property(41, String.class, "tag9F39", false, "TAG9F39");
        public final static Property TimeStamp = new Property(42, java.util.Date.class, "timeStamp", false, "TIME_STAMP");
    }


    public EMVBatchUploadDataDao(DaoConfig config) {
        super(config);
    }
    
    public EMVBatchUploadDataDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"EMVBatchUploadData\" (" + //
                "\"_id\" INTEGER PRIMARY KEY AUTOINCREMENT ," + // 0: id
                "\"TAG82\" TEXT," + // 1: tag82
                "\"TAG9F36\" TEXT," + // 2: tag9F36
                "\"TAG9F07\" TEXT," + // 3: tag9F07
                "\"TAG9F27\" TEXT," + // 4: tag9F27
                "\"TAG8E\" TEXT," + // 5: tag8E
                "\"TAG9F34\" TEXT," + // 6: tag9F34
                "\"TAG9F1E\" TEXT," + // 7: tag9F1E
                "\"TAG9F0D\" TEXT," + // 8: tag9F0D
                "\"TAG9F0E\" TEXT," + // 9: tag9F0E
                "\"TAG9F0F\" TEXT," + // 10: tag9F0F
                "\"TAG9F10\" TEXT," + // 11: tag9F10
                "\"TAGDF31\" TEXT," + // 12: tagDF31
                "\"TAG9F33\" TEXT," + // 13: tag9F33
                "\"TAG9F35\" TEXT," + // 14: tag9F35
                "\"TAG95\" TEXT," + // 15: tag95
                "\"TAG9B\" TEXT," + // 16: tag9B
                "\"TAG9F26\" TEXT," + // 17: tag9F26
                "\"TAG9F37\" TEXT," + // 18: tag9F37
                "\"TAG9F01\" TEXT," + // 19: tag9F01
                "\"TAG9F02\" TEXT," + // 20: tag9F02
                "\"TAG9F03\" TEXT," + // 21: tag9F03
                "\"TAG5F25\" TEXT," + // 22: tag5F25
                "\"TAG5F24\" TEXT," + // 23: tag5F24
                "\"TAG5A\" TEXT," + // 24: tag5A
                "\"TAG5F34\" TEXT," + // 25: tag5F34
                "\"TAG5F28\" TEXT," + // 26: tag5F28
                "\"TAG9F15\" TEXT," + // 27: tag9F15
                "\"TAG9F16\" TEXT," + // 28: tag9F16
                "\"TAG9F1A\" TEXT," + // 29: tag9F1A
                "\"TAG9F1C\" TEXT," + // 30: tag9F1C
                "\"TAG57\" TEXT," + // 31: tag57
                "\"TAG81\" TEXT," + // 32: tag81
                "\"TAG5F2A\" TEXT," + // 33: tag5F2A
                "\"TAG9A\" TEXT," + // 34: tag9A
                "\"TAG9F21\" TEXT," + // 35: tag9F21
                "\"TAG9C\" TEXT," + // 36: tag9C
                "\"TAG9F24\" TEXT," + // 37: tag9F24
                "\"TAG9F19\" TEXT," + // 38: tag9F19
                "\"TAG9F06\" TEXT," + // 39: tag9F06
                "\"TAG8A\" TEXT," + // 40: tag8A
                "\"TAG9F39\" TEXT," + // 41: tag9F39
                "\"TIME_STAMP\" INTEGER);"); // 42: timeStamp
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"EMVBatchUploadData\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, EMVBatchUploadData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String tag82 = entity.getTag82();
        if (tag82 != null) {
            stmt.bindString(2, tag82);
        }
 
        String tag9F36 = entity.getTag9F36();
        if (tag9F36 != null) {
            stmt.bindString(3, tag9F36);
        }
 
        String tag9F07 = entity.getTag9F07();
        if (tag9F07 != null) {
            stmt.bindString(4, tag9F07);
        }
 
        String tag9F27 = entity.getTag9F27();
        if (tag9F27 != null) {
            stmt.bindString(5, tag9F27);
        }
 
        String tag8E = entity.getTag8E();
        if (tag8E != null) {
            stmt.bindString(6, tag8E);
        }
 
        String tag9F34 = entity.getTag9F34();
        if (tag9F34 != null) {
            stmt.bindString(7, tag9F34);
        }
 
        String tag9F1E = entity.getTag9F1E();
        if (tag9F1E != null) {
            stmt.bindString(8, tag9F1E);
        }
 
        String tag9F0D = entity.getTag9F0D();
        if (tag9F0D != null) {
            stmt.bindString(9, tag9F0D);
        }
 
        String tag9F0E = entity.getTag9F0E();
        if (tag9F0E != null) {
            stmt.bindString(10, tag9F0E);
        }
 
        String tag9F0F = entity.getTag9F0F();
        if (tag9F0F != null) {
            stmt.bindString(11, tag9F0F);
        }
 
        String tag9F10 = entity.getTag9F10();
        if (tag9F10 != null) {
            stmt.bindString(12, tag9F10);
        }
 
        String tagDF31 = entity.getTagDF31();
        if (tagDF31 != null) {
            stmt.bindString(13, tagDF31);
        }
 
        String tag9F33 = entity.getTag9F33();
        if (tag9F33 != null) {
            stmt.bindString(14, tag9F33);
        }
 
        String tag9F35 = entity.getTag9F35();
        if (tag9F35 != null) {
            stmt.bindString(15, tag9F35);
        }
 
        String tag95 = entity.getTag95();
        if (tag95 != null) {
            stmt.bindString(16, tag95);
        }
 
        String tag9B = entity.getTag9B();
        if (tag9B != null) {
            stmt.bindString(17, tag9B);
        }
 
        String tag9F26 = entity.getTag9F26();
        if (tag9F26 != null) {
            stmt.bindString(18, tag9F26);
        }
 
        String tag9F37 = entity.getTag9F37();
        if (tag9F37 != null) {
            stmt.bindString(19, tag9F37);
        }
 
        String tag9F01 = entity.getTag9F01();
        if (tag9F01 != null) {
            stmt.bindString(20, tag9F01);
        }
 
        String tag9F02 = entity.getTag9F02();
        if (tag9F02 != null) {
            stmt.bindString(21, tag9F02);
        }
 
        String tag9F03 = entity.getTag9F03();
        if (tag9F03 != null) {
            stmt.bindString(22, tag9F03);
        }
 
        String tag5F25 = entity.getTag5F25();
        if (tag5F25 != null) {
            stmt.bindString(23, tag5F25);
        }
 
        String tag5F24 = entity.getTag5F24();
        if (tag5F24 != null) {
            stmt.bindString(24, tag5F24);
        }
 
        String tag5A = entity.getTag5A();
        if (tag5A != null) {
            stmt.bindString(25, tag5A);
        }
 
        String tag5F34 = entity.getTag5F34();
        if (tag5F34 != null) {
            stmt.bindString(26, tag5F34);
        }
 
        String tag5F28 = entity.getTag5F28();
        if (tag5F28 != null) {
            stmt.bindString(27, tag5F28);
        }
 
        String tag9F15 = entity.getTag9F15();
        if (tag9F15 != null) {
            stmt.bindString(28, tag9F15);
        }
 
        String tag9F16 = entity.getTag9F16();
        if (tag9F16 != null) {
            stmt.bindString(29, tag9F16);
        }
 
        String tag9F1A = entity.getTag9F1A();
        if (tag9F1A != null) {
            stmt.bindString(30, tag9F1A);
        }
 
        String tag9F1C = entity.getTag9F1C();
        if (tag9F1C != null) {
            stmt.bindString(31, tag9F1C);
        }
 
        String tag57 = entity.getTag57();
        if (tag57 != null) {
            stmt.bindString(32, tag57);
        }
 
        String tag81 = entity.getTag81();
        if (tag81 != null) {
            stmt.bindString(33, tag81);
        }
 
        String tag5F2A = entity.getTag5F2A();
        if (tag5F2A != null) {
            stmt.bindString(34, tag5F2A);
        }
 
        String tag9A = entity.getTag9A();
        if (tag9A != null) {
            stmt.bindString(35, tag9A);
        }
 
        String tag9F21 = entity.getTag9F21();
        if (tag9F21 != null) {
            stmt.bindString(36, tag9F21);
        }
 
        String tag9C = entity.getTag9C();
        if (tag9C != null) {
            stmt.bindString(37, tag9C);
        }
 
        String tag9F24 = entity.getTag9F24();
        if (tag9F24 != null) {
            stmt.bindString(38, tag9F24);
        }
 
        String tag9F19 = entity.getTag9F19();
        if (tag9F19 != null) {
            stmt.bindString(39, tag9F19);
        }
 
        String tag9F06 = entity.getTag9F06();
        if (tag9F06 != null) {
            stmt.bindString(40, tag9F06);
        }
 
        String tag8A = entity.getTag8A();
        if (tag8A != null) {
            stmt.bindString(41, tag8A);
        }
 
        String tag9F39 = entity.getTag9F39();
        if (tag9F39 != null) {
            stmt.bindString(42, tag9F39);
        }
 
        java.util.Date timeStamp = entity.getTimeStamp();
        if (timeStamp != null) {
            stmt.bindLong(43, timeStamp.getTime());
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, EMVBatchUploadData entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String tag82 = entity.getTag82();
        if (tag82 != null) {
            stmt.bindString(2, tag82);
        }
 
        String tag9F36 = entity.getTag9F36();
        if (tag9F36 != null) {
            stmt.bindString(3, tag9F36);
        }
 
        String tag9F07 = entity.getTag9F07();
        if (tag9F07 != null) {
            stmt.bindString(4, tag9F07);
        }
 
        String tag9F27 = entity.getTag9F27();
        if (tag9F27 != null) {
            stmt.bindString(5, tag9F27);
        }
 
        String tag8E = entity.getTag8E();
        if (tag8E != null) {
            stmt.bindString(6, tag8E);
        }
 
        String tag9F34 = entity.getTag9F34();
        if (tag9F34 != null) {
            stmt.bindString(7, tag9F34);
        }
 
        String tag9F1E = entity.getTag9F1E();
        if (tag9F1E != null) {
            stmt.bindString(8, tag9F1E);
        }
 
        String tag9F0D = entity.getTag9F0D();
        if (tag9F0D != null) {
            stmt.bindString(9, tag9F0D);
        }
 
        String tag9F0E = entity.getTag9F0E();
        if (tag9F0E != null) {
            stmt.bindString(10, tag9F0E);
        }
 
        String tag9F0F = entity.getTag9F0F();
        if (tag9F0F != null) {
            stmt.bindString(11, tag9F0F);
        }
 
        String tag9F10 = entity.getTag9F10();
        if (tag9F10 != null) {
            stmt.bindString(12, tag9F10);
        }
 
        String tagDF31 = entity.getTagDF31();
        if (tagDF31 != null) {
            stmt.bindString(13, tagDF31);
        }
 
        String tag9F33 = entity.getTag9F33();
        if (tag9F33 != null) {
            stmt.bindString(14, tag9F33);
        }
 
        String tag9F35 = entity.getTag9F35();
        if (tag9F35 != null) {
            stmt.bindString(15, tag9F35);
        }
 
        String tag95 = entity.getTag95();
        if (tag95 != null) {
            stmt.bindString(16, tag95);
        }
 
        String tag9B = entity.getTag9B();
        if (tag9B != null) {
            stmt.bindString(17, tag9B);
        }
 
        String tag9F26 = entity.getTag9F26();
        if (tag9F26 != null) {
            stmt.bindString(18, tag9F26);
        }
 
        String tag9F37 = entity.getTag9F37();
        if (tag9F37 != null) {
            stmt.bindString(19, tag9F37);
        }
 
        String tag9F01 = entity.getTag9F01();
        if (tag9F01 != null) {
            stmt.bindString(20, tag9F01);
        }
 
        String tag9F02 = entity.getTag9F02();
        if (tag9F02 != null) {
            stmt.bindString(21, tag9F02);
        }
 
        String tag9F03 = entity.getTag9F03();
        if (tag9F03 != null) {
            stmt.bindString(22, tag9F03);
        }
 
        String tag5F25 = entity.getTag5F25();
        if (tag5F25 != null) {
            stmt.bindString(23, tag5F25);
        }
 
        String tag5F24 = entity.getTag5F24();
        if (tag5F24 != null) {
            stmt.bindString(24, tag5F24);
        }
 
        String tag5A = entity.getTag5A();
        if (tag5A != null) {
            stmt.bindString(25, tag5A);
        }
 
        String tag5F34 = entity.getTag5F34();
        if (tag5F34 != null) {
            stmt.bindString(26, tag5F34);
        }
 
        String tag5F28 = entity.getTag5F28();
        if (tag5F28 != null) {
            stmt.bindString(27, tag5F28);
        }
 
        String tag9F15 = entity.getTag9F15();
        if (tag9F15 != null) {
            stmt.bindString(28, tag9F15);
        }
 
        String tag9F16 = entity.getTag9F16();
        if (tag9F16 != null) {
            stmt.bindString(29, tag9F16);
        }
 
        String tag9F1A = entity.getTag9F1A();
        if (tag9F1A != null) {
            stmt.bindString(30, tag9F1A);
        }
 
        String tag9F1C = entity.getTag9F1C();
        if (tag9F1C != null) {
            stmt.bindString(31, tag9F1C);
        }
 
        String tag57 = entity.getTag57();
        if (tag57 != null) {
            stmt.bindString(32, tag57);
        }
 
        String tag81 = entity.getTag81();
        if (tag81 != null) {
            stmt.bindString(33, tag81);
        }
 
        String tag5F2A = entity.getTag5F2A();
        if (tag5F2A != null) {
            stmt.bindString(34, tag5F2A);
        }
 
        String tag9A = entity.getTag9A();
        if (tag9A != null) {
            stmt.bindString(35, tag9A);
        }
 
        String tag9F21 = entity.getTag9F21();
        if (tag9F21 != null) {
            stmt.bindString(36, tag9F21);
        }
 
        String tag9C = entity.getTag9C();
        if (tag9C != null) {
            stmt.bindString(37, tag9C);
        }
 
        String tag9F24 = entity.getTag9F24();
        if (tag9F24 != null) {
            stmt.bindString(38, tag9F24);
        }
 
        String tag9F19 = entity.getTag9F19();
        if (tag9F19 != null) {
            stmt.bindString(39, tag9F19);
        }
 
        String tag9F06 = entity.getTag9F06();
        if (tag9F06 != null) {
            stmt.bindString(40, tag9F06);
        }
 
        String tag8A = entity.getTag8A();
        if (tag8A != null) {
            stmt.bindString(41, tag8A);
        }
 
        String tag9F39 = entity.getTag9F39();
        if (tag9F39 != null) {
            stmt.bindString(42, tag9F39);
        }
 
        java.util.Date timeStamp = entity.getTimeStamp();
        if (timeStamp != null) {
            stmt.bindLong(43, timeStamp.getTime());
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public EMVBatchUploadData readEntity(Cursor cursor, int offset) {
        EMVBatchUploadData entity = new EMVBatchUploadData( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // tag82
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // tag9F36
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // tag9F07
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // tag9F27
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // tag8E
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // tag9F34
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // tag9F1E
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // tag9F0D
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // tag9F0E
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // tag9F0F
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // tag9F10
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // tagDF31
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // tag9F33
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // tag9F35
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // tag95
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // tag9B
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // tag9F26
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // tag9F37
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // tag9F01
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // tag9F02
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // tag9F03
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // tag5F25
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // tag5F24
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // tag5A
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // tag5F34
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // tag5F28
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // tag9F15
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // tag9F16
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // tag9F1A
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // tag9F1C
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // tag57
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // tag81
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // tag5F2A
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // tag9A
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // tag9F21
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // tag9C
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // tag9F24
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // tag9F19
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // tag9F06
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // tag8A
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41), // tag9F39
            cursor.isNull(offset + 42) ? null : new java.util.Date(cursor.getLong(offset + 42)) // timeStamp
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, EMVBatchUploadData entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setTag82(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setTag9F36(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setTag9F07(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setTag9F27(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTag8E(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setTag9F34(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setTag9F1E(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setTag9F0D(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setTag9F0E(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTag9F0F(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setTag9F10(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTagDF31(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setTag9F33(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setTag9F35(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setTag95(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setTag9B(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setTag9F26(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setTag9F37(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setTag9F01(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setTag9F02(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setTag9F03(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setTag5F25(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setTag5F24(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setTag5A(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setTag5F34(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setTag5F28(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setTag9F15(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setTag9F16(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setTag9F1A(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setTag9F1C(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setTag57(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setTag81(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setTag5F2A(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setTag9A(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setTag9F21(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setTag9C(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setTag9F24(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setTag9F19(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setTag9F06(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setTag8A(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setTag9F39(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
        entity.setTimeStamp(cursor.isNull(offset + 42) ? null : new java.util.Date(cursor.getLong(offset + 42)));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(EMVBatchUploadData entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(EMVBatchUploadData entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(EMVBatchUploadData entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
